"""Generate a checked C3 BLE-Gamepad-Client stack-size adaptation at build time.

Register as ``extra_scripts = pre:tools/pio_ble_task_stack.py``. Only C3
compilations substitute generated copies; installed library files stay intact.
``ANTCORE_BLE_TASK_STACK_SIZE`` defaults to the upstream 10000 bytes, and the
C3 PlatformIO environment explicitly selects 4096 bytes.

Standalone validation (does not compile firmware or access hardware):
    python tools/pio_ble_task_stack.py --check <BLE-Gamepad-Client directory>
    python tools/pio_ble_task_stack.py --check <directory> --self-test
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import tempfile
from pathlib import Path
from typing import Any


LIBRARY_NAME = "BLE-Gamepad-Client"
LIBRARY_VERSION = "0.12.1"
STACK_MACRO = "ANTCORE_BLE_TASK_STACK_SIZE"
C3_BOARD = "seeed_xiao_esp32c3"

# SHA256 of the pinned upstream sources after universal-newline decoding.
# Upstream changes must be reviewed explicitly instead of silently repatched.
SOURCE_HASHES = {
    "BLEAutoScan.cpp": "328060b40391fbcffc60b3ebd610ec9d217d322edb19d9ff0c61cd23fa255cb6",
    "BLEControllerRegistry.cpp": "5d1bd3e4b1945915abdc3f0d40d840171c59b66dec3976ca84bcea3e9098fe8b",
    "BLEUserCallbackRunner.cpp": "9e35bb6a41e6621e4504744b441714981a13f741e94d931c446e4141c74798bd",
    "BLEValueReceiver.cpp": "e9b3a1a6c718780252f565cd6c48c7983cfebf449f164663e8435ddbca9a1a62",
    "BLEValueWriter.cpp": "9de32f845e861b7c500ad609951f3d923bbf65053fca1bf21bc64e8fdd232ce6",
}

TASK_STACK = re.compile(r'(\bxTaskCreate(?:PinnedToCore)?\s*\(\s*\w+\s*,\s*"[^"\n]+"\s*,\s*)10000(\s*,)')


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def transform_source(name: str, text: str, source_path: Path) -> str:
    if name not in SOURCE_HASHES or digest(text) != SOURCE_HASHES[name]:
        raise RuntimeError(f"Ant Core BLE stack adaptation: unexpected upstream content in {name}; review pinned dependency")
    adapted, count = TASK_STACK.subn(lambda m: m.group(1) + STACK_MACRO + m.group(2), text)
    if count != 1:
        raise RuntimeError(f"Ant Core BLE stack adaptation: expected one task creation in {name}, found {count}")
    # Preserve original filenames in compiler diagnostics. Forward slashes work
    # on Windows and avoid accidental backslash escape sequences in #line.
    original = source_path.resolve().as_posix().replace('"', '\\"')
    return (
        "// Generated by tools/pio_ble_task_stack.py; installed dependency is unchanged.\n"
        f"#ifndef {STACK_MACRO}\n#define {STACK_MACRO} 10000\n#endif\n"
        f'#line 1 "{original}"\n' + adapted
    )


def validate_library(library: Path) -> dict[str, str]:
    manifest = json.loads((library / "library.json").read_text(encoding="utf-8"))
    if manifest.get("name") != LIBRARY_NAME or manifest.get("version") != LIBRARY_VERSION:
        raise RuntimeError(f"Ant Core BLE stack adaptation requires {LIBRARY_NAME} {LIBRARY_VERSION}")
    sources = {}
    for name in SOURCE_HASHES:
        path = library / "src" / name
        text = path.read_text(encoding="utf-8")
        transform_source(name, text, path)
        sources[name] = text
    return sources


def write_if_changed(path: Path, text: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def install(build_env: Any) -> None:
    # Board-based scope also works for custom environment names extending C3.
    if build_env.subst("$BOARD") != C3_BOARD:
        return
    generated_dir = Path(build_env.subst("$BUILD_DIR")) / "antcore_ble_stack"
    validated: dict[Path, dict[str, str]] = {}

    def middleware(env: Any, node: Any) -> Any:
        original = Path(node.srcnode().get_abspath())
        if original.name not in SOURCE_HASHES or original.parent.parent.name != LIBRARY_NAME:
            return node
        library = original.parent.parent
        if library not in validated:
            validated[library] = validate_library(library)
        generated = generated_dir / original.name
        write_if_changed(generated, transform_source(original.name, validated[library][original.name], original))
        # The callback receives the library's construction environment, so its
        # include paths/compiler flags (including the explicit C3 macro) apply.
        # Generated .cpp files no longer sit beside their quoted local headers.
        env.PrependUnique(CPPPATH=[str(original.parent)])
        return env.File(str(generated))

    # PRE is required: library source selection happens while BUILD_SCRIPT is
    # evaluated; a POST extra script would miss this middleware hook.
    build_env.AddBuildMiddleware(middleware)


def self_test(library: Path) -> dict[str, bool]:
    original_bytes = {name: (library / "src" / name).read_bytes() for name in SOURCE_HASHES}
    sources = validate_library(library)
    checks = {}
    transformed = {name: transform_source(name, text, library / "src" / name) for name, text in sources.items()}
    checks["all_five_task_sites_configurable"] = all(
        len(re.findall(r'\bxTaskCreate(?:PinnedToCore)?\s*\([^;]+\b' + STACK_MACRO + r'\b', text)) == 1
        and TASK_STACK.search(text) is None for text in transformed.values()
    )
    checks["upstream_stack_default_preserved"] = all(
        f"#ifndef {STACK_MACRO}\n#define {STACK_MACRO} 10000\n#endif" in text for text in transformed.values()
    )
    try:
        transform_source("BLEAutoScan.cpp", sources["BLEAutoScan.cpp"] + "// changed", library / "src" / "BLEAutoScan.cpp")
    except RuntimeError:
        checks["changed_upstream_source_rejected"] = True
    else:
        checks["changed_upstream_source_rejected"] = False

    class FakeNode:
        def __init__(self, path):
            self.path = Path(path)

        def srcnode(self):
            return self

        def get_abspath(self):
            return str(self.path.resolve())

    class FakeEnv:
        def __init__(self, board, build):
            self.board, self.build, self.callbacks, self.include_paths = board, build, [], []

        def subst(self, variable):
            return self.board if variable == "$BOARD" else str(self.build)

        def AddBuildMiddleware(self, callback):
            self.callbacks.append(callback)

        def File(self, path):
            return FakeNode(path)

        def PrependUnique(self, CPPPATH):
            self.include_paths = list(dict.fromkeys(CPPPATH + self.include_paths))

    with tempfile.TemporaryDirectory(prefix="antcore-ble-adaptation-check-") as temp:
        build = Path(temp)
        s3 = FakeEnv("seeed_xiao_esp32s3", build / "s3")
        install(s3)
        checks["s3_unchanged"] = not s3.callbacks and not (build / "s3").exists()
        c3 = FakeEnv(C3_BOARD, build / "c3")
        install(c3)
        callback = c3.callbacks[0]
        unchanged = FakeNode(library / "src" / "BLEGamepadClient.cpp")
        checks["unrelated_sources_unchanged"] = callback(c3, unchanged) is unchanged
        generated_ok = True
        stable_mtimes = True
        for name in SOURCE_HASHES:
            result = callback(c3, FakeNode(library / "src" / name))
            generated = Path(result.get_abspath())
            generated_ok &= generated.is_relative_to(build) and generated.read_text(encoding="utf-8") == transformed[name]
            mtime = generated.stat().st_mtime_ns
            callback(c3, FakeNode(library / "src" / name))
            stable_mtimes &= generated.stat().st_mtime_ns == mtime
        checks["generated_copies_only_in_build_dir"] = generated_ok
        checks["generation_is_idempotent"] = stable_mtimes
        checks["original_relative_include_paths_preserved"] = str((library / "src").resolve()) in c3.include_paths
        bad_library = build / "wrong-version"
        bad_library.mkdir()
        (bad_library / "library.json").write_text(json.dumps({"name": LIBRARY_NAME, "version": "9.9.9"}), encoding="utf-8")
        try:
            validate_library(bad_library)
        except RuntimeError:
            checks["different_dependency_version_rejected"] = True
        else:
            checks["different_dependency_version_rejected"] = False
    checks["installed_library_bytes_preserved"] = all(
        (library / "src" / name).read_bytes() == before for name, before in original_bytes.items()
    )
    return checks


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", required=True, type=Path, help="Installed BLE-Gamepad-Client directory")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    sources = validate_library(args.check)
    checks = self_test(args.check) if args.self_test else {}
    print(json.dumps({"library": LIBRARY_NAME, "version": LIBRARY_VERSION,
                      "verifiedSourceFiles": len(sources), "checks": checks,
                      "passed": all(checks.values())}, indent=2))
    return 0 if all(checks.values()) else 1


if "Import" in globals():
    Import("env")  # type: ignore[name-defined]  # Supplied by PlatformIO/SCons.
    install(env)  # type: ignore[name-defined]
elif __name__ == "__main__":
    raise SystemExit(main())
